### ISSUE TITLE
Horizontal scrollbar on Windows

### ISSUE THREAD

**Issue by simevidas** [kingdido999/zooming#10]
I’ve tested the demo in my browsers on Windows 10, and when zooming in on an image, the horizontal scrollbar appears. I *think* this is because on Windows scrollbars take up space, and on Mac they don’t (they’re overlaid), so your calculation is incorrect on Windows. Just a guess!

![scrollbar](https://cloud.githubusercontent.com/assets/716405/21448705/d69d8204-c8e5-11e6-932e-288eaaca7892.png)

**Comment by kingdido999** [comment]
@simevidas From the screenshot I can tell it's over zoomed in on your machine, that's why the horizontal bar appears. I'll take a look.

**Comment by kingdido999** [comment]
@simevidas I excluded the space of scrollbar while calculating the window center, please check if it fixes the issue.

**Comment by simevidas** [comment]
The horizontal scrollbar is gone! Thanks for fixing.
