### ISSUE TITLE
add feature caption on photo

### ISSUE THREAD

**Issue by blackinitial** [kingdido999/zooming#114]
add feature caption on photo please,
or how to add caption on photo when zoomed

**Comment by kingdido999** [comment]
Can you be more specific? You want to display some kind of text along with the photo?

**Comment by blackinitial** [comment]
Yeah, i want to display some text (caption) when opened the image.;

**Comment by kingdido999** [comment]
The library itself will not support this feature, but it should be possible to add text via DOM manipulation in `onOpen` [event hook](https://desmonding.me/zooming/docs/#/configuration?id=event-hooks):

```js
new Zooming({
  onOpen: function (target) {
    // Add caption...
  },
  onClose: function (target) {
    // Remove caption...
  }
})
```

**Comment by blackinitial** [comment]
i have made it, but the text caption on under image (look so bad), how the text caption to the top and follow the image

![zoom photo](https://user-images.githubusercontent.com/21137500/50669743-90ac6000-0ff9-11e9-8798-faf4f40c53e7.png)
