### ISSUE TITLE
there is differents between 2 situations

### ISSUE THREAD

**Issue by qianxiaocang** [kingdido999/zooming#159]
### the first clicked photos ,the log like that:

onBeforeOpen===> <img src=​"images/​servers_img1.gif" id=​"servers_img1" class=​"servers_img" **_style=​"cursor:​ grab;​ position:​ relative;​ z-index:​ 999;​ height:​ 55.7813px;​ width:​ 262.5px;​ transition:​ transform 0.4s cubic-bezier(0.4, 0, 0, 1)​ 0s;​ transform:​ translate3d(0px, 3.60938px, 0px)​ scale(1.42857, 1.42857)​;​"_**>​
onOpen===> <img src=​"images/​servers_img1.gif" id=​"servers_img1" class=​"servers_img" style=​"cursor:​ grab;​ position:​ relative;​ z-index:​ 999;​ height:​ 55.7813px;​ width:​ 262.5px;​ transition:​ transform 0.4s cubic-bezier(0.4, 0, 0, 1)​ 0s;​ transform:​ translate3d(0px, 3.60938px, 0px)​ scale(1.42857, 1.42857)​;​">​
onBeforeClose===> <img src=​"​images/​servers_img1.png" id=​"servers_img1" class=​"servers_img" style=​"cursor:​ grab;​ position:​ relative;​ z-index:​ 999;​ height:​ 55.7813px;​ width:​ 262.5px;​ transition:​ transform 0.4s cubic-bezier(0.4, 0, 0, 1)​ 0s;​ transform:​ translate3d(0px, 3.60938px, 0px)​ scale(1.42857, 1.42857)​;​">​
onClose===> <img src=​"​images/​servers_img1.png" id=​"servers_img1" class=​"servers_img" style=​"cursor:​ grab;​ position:​ relative;​ z-index:​ 999;​ height:​ 55.7813px;​ width:​ 262.5px;​ transition:​ transform 0.4s cubic-bezier(0.4, 0, 0, 1)​ 0s;​ transform:​ none;​">​

### the second clicked photos ,the log like that:

onBeforeOpen===> <img src=​"images/​servers_img1.gif" id=​"servers_img1" class=​"servers_img" **_style=​"cursor:​ zoom-in;​"_**>​
 onOpen===> <img src=​"images/​servers_img1.gif" id=​"servers_img1" class=​"servers_img" style=​"cursor:​ grab;​ position:​ relative;​ z-index:​ 999;​ height:​ 466.547px;​ width:​ 262.5px;​ transition:​ transform 0.4s cubic-bezier(0.4, 0, 0, 1)​ 0s;​ transform:​ translate3d(0px, -201.773px, 0px)​ scale(1.42857, 1.42857)​;​">​
onBeforeClose===> <img src=​"​images/​servers_img1.png" id=​"servers_img1" class=​"servers_img" style=​"cursor:​ grab;​ position:​ relative;​ z-index:​ 999;​ height:​ 466.547px;​ width:​ 262.5px;​ transition:​ transform 0.4s cubic-bezier(0.4, 0, 0, 1)​ 0s;​ transform:​ translate3d(0px, -201.773px, 0px)​ scale(1.42857, 1.42857)​;​">​
onClose===> <img src=​"​images/​servers_img1.png" id=​"servers_img1" class=​"servers_img" style=​"cursor:​ grab;​ position:​ relative;​ z-index:​ 999;​ height:​ 466.547px;​ width:​ 262.5px;​ transition:​ transform 0.4s cubic-bezier(0.4, 0, 0, 1)​ 0s;​ transform:​ none;​">​

i just want to open the another photo by `zooming.listen('.servers_img')` , and then it can be opening full screen,but it always fail in opening when it has be opened in first,please help me to fixed this ,THX!

**Comment by kingdido999** [comment]
I'm not sure what you meant, can you reproduce this in [codepen](https://codepen.io/kingdido999/pen/rpYrKV)? Feel free to reopen once you have a reproducible demo.
