### ISSUE TITLE
it did not work for me

### ISSUE THREAD

**Issue by jerryc127** [kingdido999/zooming#167]
Make sure the bug can be reproduced in either [demo](http://desmonding.me/zooming/) page or a forked [codepen](https://codepen.io/kingdido999/pen/rpYrKV) page.

**Describe the bug**

**To Reproduce**
1.

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

it did not work, i click the img, it nothing happen.

i do not how to solve it

![image](https://user-images.githubusercontent.com/16351105/57571599-c39caf80-7442-11e9-9a31-3a20570efbe8.png)
![image](https://user-images.githubusercontent.com/16351105/57571627-0b233b80-7443-11e9-9897-27696734db8f.png)

**Comment by jerryc127** [comment]
finally, it work now
![image](https://user-images.githubusercontent.com/16351105/57571699-e4b1d000-7443-11e9-9dbd-33282e195a15.png)
but why the way of the document  is did not work for me
![image](https://user-images.githubusercontent.com/16351105/57571719-12971480-7444-11e9-959f-b74dfc62a284.png)

**Comment by kingdido999** [comment]
Are you sure you're using `.img-zoomable` instead of `img-zoomable` css selector for the document example?
