### ISSUE TITLE
Zoom out on clicking on a zoomed in image

### ISSUE THREAD

**Issue by chokolade** [kingdido999/zooming#21]
Didn't the earlier version of the plugin allow to zoom out(close) on clicking a zoomed in image.That doesn't seem to work now.

**Comment by kingdido999** [comment]
It's working for me. Please provide module version, browser version and OS that does not work for you.

**Comment by chokolade** [comment]
Yes right now only clicking outside the image is closing the image for me not clicking the zoomed image in itself.
What do you mean by module version
Browser : Chrome; OS: Windows 8

**Comment by kingdido999** [comment]
You mean the [demo](http://desmonding.me/zooming/) page is not working for you right? Can you try different browsers, like Firefox and IE (10+), to see if they work or not?

**Comment by chokolade** [comment]
yes the demo page is not working. I tried in firefox, Chrome the image closes on clicking outside the image but not clicking inside the zoomed in image

**Comment by kingdido999** [comment]
I do not have the device to reproduce this issue. It would be great if you can pull the latest code and see if it works on your local.

**Comment by chokolade** [comment]
Closing the issue since it is working now.
