### ISSUE TITLE
Wrong vertical center

### ISSUE THREAD

**Issue by kobeaerts** [kingdido999/zooming#24]
Hey, I have an issue with the latest version (1.0.9), the images don't appear in the middle of the screen because the windowCenter function returns a "wrong" value, if I change the code to the one below it does take the correct windowCenter:

```
function getWindowCenter() {
        var docWidth = docElm.clientWidth || body.clientWidth;
        var docHeight = window.innerHeight; // this didn't work: docElm.clientHeight || body.clientHeight;

        return {
            x: half(docWidth),
            y: half(docHeight)
        };
    }
```

**Comment by kingdido999** [comment]
It would be great if you can show me a specific example with correct height vs "wrong" height and why did you think it's a "wrong" value. Please also provide OS and browsers having this issue.

**Comment by kobeaerts** [comment]
Hmm, don't have anything online atm. But I'm developing in the latest version of Chrome on my MacBook.

I think this function should give you the center of your screen/window but atm it gives you the center of your entire document. 

If for example I style my body to be 4000px, this center function will give 2000px as vertical center which is not the center of my window (lets say my window is 960px high, it should be 480px).

**Comment by kingdido999** [comment]
@kobeaerts Please verify the fix in [demo](http://desmonding.me/zooming/) works for you. I'm suspecting your browser somehow skipped `document.documentElement.clientHeight` and went for the value of `document.body.clientHeight`.

**Comment by kobeaerts** [comment]
It works!

**Comment by kingdido999** [comment]
The current implementation is below:

```js
function getWindowCenter () {
  const windowWidth = Math.min(docElm.clientWidth, window.innerWidth)
  const windowHeight = Math.min(docElm.clientHeight, window.innerHeight)

  return {
    x: half(windowWidth),
    y: half(windowHeight)
  }
}
```

Notice it's not perfect though, in modern browsers, it will give you the window center that either excludes scroll bar width and height, which are the desired values, or includes scroll bar width and height (`window.innerWidth` and `window.innerHeight`).

References:
- [Element.clientHeight](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight)
- [Window.innerHeight](https://developer.mozilla.org/en-US/docs/Web/API/Window/innerHeight)
