### ISSUE TITLE
Acess the template wrapper

### ISSUE THREAD

**Issue by Giovancruz** [kingdido999/zooming#243]
How can i do to have acess on the div that wrapp the image on zoom?

I want to put a text like legend on user open zooming. But the div is created on click, without class or return in the onOpen function.

**Comment by kingdido999** [comment]
Are you referring to the overlay div? Actually there is no wrapper for the image at all when zooming in. Depending on how do you want to place the text (whether fixed position or relative to the image), you can programmatically create the legend element inside the `onOpen` callback. Make sure the element has `z-index` value greater or equal to the image's (default value: 999).

Let me know if you need further help.
