### ISSUE TITLE
Is it possible to disable on mobile?

### ISSUE THREAD

**Issue by ads1018** [kingdido999/zooming#26]

**Comment by kingdido999** [comment]
It will not provide such functionality. There are some libs that detect mobile devices, you should really use one of them or implement it by yourself to best suit your needs.

**Comment by p-4** [comment]
I have spent more than a day trying to figure out how to do this, so I am posting this for future reference for the less experienced on how to load zooming conditionally.

In this case on screens bigger than certain amount of pixels.

Here is the original question:
https://stackoverflow.com/questions/49572604/loading-a-js-file-conditionally-how

And here the final result. Loads zooming if browser window width is more than 500px:
https://codepen.io/zuhocuyixu/pen/wmmyOZ
