### ISSUE TITLE
Angularjs 2 Webpack and jade/pug, this is not working

### ISSUE THREAD

**Issue by luismiguelbravo** [kingdido999/zooming#27]
For feature request or questions, ignore everything below.

For any issue related to [demo](http://desmonding.me/zooming/) page, please include the following details:

- OS:  Linux
- Steps to reproduce:
npm install zooming --save

add reference in archive app.module.ts
import { Zooming } from 'zooming';

add data-action to an image in .pug file
img.img-responsive([src]="imageZoomText.imagePath", data-action="zoom" )

Additional comments:
hello, this is not working
![captura de pantalla de 2017-02-13 15-51-03](https://cloud.githubusercontent.com/assets/5140529/22897916/3f8d19fe-f204-11e6-83df-36407d7734b2.png)
![captura de pantalla de 2017-02-13 15-50-27](https://cloud.githubusercontent.com/assets/5140529/22897917/3f8d0b12-f204-11e6-8c5d-e787bef74480.png)

**Comment by kingdido999** [comment]
@luismiguelbravo Try `import Zooming from 'zooming'`.
