### ISSUE TITLE
ie11 compatibility

### ISSUE THREAD

**Issue by pkers87** [kingdido999/zooming#28]
hi, 
i was testing this library on same browsers: chrome 56, firefox 51, edge and ie11.
everything works fine except in ie, showing this kind of error in console:

> SCRIPT438: Object doesn't support this property or method
> zooming.js (914,5)

i think this line break the script
`this.options = Object.assign({}, OPTIONS);`

thanks for your work!

**Comment by kingdido999** [comment]
@pkers87 Thanks for the feedback! Please check if the issue was resolved in IE.

**Comment by pkers87** [comment]
it works! thanks!
