### ISSUE TITLE
Support question: is lazy loading possible for data-original?

### ISSUE THREAD

**Issue by janlemmens** [kingdido999/zooming#29]
At this moment, the image referenced in the data-original attribute is loaded on page load. Is it possible to lazy load that image when activating zoom? Any plans to add this functionality in the future?

Kind regards,
Jan

**Comment by kingdido999** [comment]
@janlemmens The option `preloadImage` is enabled by default. You can set it to `false` so that it loads `data-original` only after it starts zooming in:

```js
const zooming = new Zooming({
  preloadImage: false
})
```

**Comment by janlemmens** [comment]
Great! Thanks for the quick feedback. Must have missed that setting. Nice work on the library btw!
