### ISSUE TITLE
zooming videos

### ISSUE THREAD

**Issue by medakk** [kingdido999/zooming#303]
> Before you submit a feature request, please make sure to read through [Documentation](http://desmonding.me/zooming/docs/index.html).

^ that link is broken

**Is your feature request related to a problem? Please describe.**
It would be nice if I could zooming would work on `<video>` and not just image.

**Describe the solution you'd like**
Same behaviour as image. When I click the video, it transitions to full screen.

**Comment by kingdido999** [comment]
Thanks for pointing out he broken link, it should work now. Regarding zooming on video element, it should be possible but I'm not sure if that's a useful/desirable effect to users since video element has native support for full-screen mode.

**Comment by medakk** [comment]
My use case is that I have a sort of "gallery"(a scrollable list of images) with mostly images but with a few GIFs(mp4s really) interspersed(with controls disabled). I use zooming to allow the user to zoom into the images. It would be nice if I could accomplish the same for videos via zooming.js, even if it just delegates to the native full screen mode. 

It should be straightforward to implement in vanilla js, and if it doesn't fit the ethos of this library, I'll just do that.

**Comment by kingdido999** [comment]
I'd say it's best to implement that functionality using some custom js code.

**Comment by medakk** [comment]
Sure. Thanks!
