### ISSUE TITLE
click once to resize

### ISSUE THREAD

**Issue by johnson329** [kingdido999/zooming#327]
by default i need to double click to close picture or zoom？
i want to click once to close
how can i do that？
thx in advance

**Comment by kingdido999** [comment]
The current behavior is indeed clicking once to open/close. Please provide more details on reproducing your issue.

**Comment by johnson329** [comment]
> The current behavior is indeed clicking once to open/close. Please provide more details on reproducing your issue.

oh it's strange
when I use TouchPad with my laptop,I must click twice to close picture,sometimes can not close
when I use mouse,everything is correct

**Comment by kingdido999** [comment]
Hmm...I'm not sure if I can help with this issue. Could it be your TouchPad issue since your mouse is working fine?

**Comment by johnson329** [comment]
may be
anyway thx
