### ISSUE TITLE
Thanks for an excellent tool!

### ISSUE THREAD

**Issue by briwagner** [kingdido999/zooming#328]
Just wanted to say this is an amazing tool! Thanks for building and maintaining this. The docs are great, and the API is really clear about how to use and customize. I just dropped this into a project in a couple hours and boom, it works.

Thanks. Keep up the great work!

Brian

**Comment by kingdido999** [comment]
Hey Brian, I'm very glad it worked out for you and your kind words literally made my day! 😄
