### ISSUE TITLE
(bug) Wrong opened image scaling if initial and original images has different aspect ratio

### ISSUE THREAD

**Issue by artaommahe** [kingdido999/zooming#33]
I see an issue in page:
https://codepen.io/anon/pen/jmYLqb?editors=1010

- OS:  Ubuntu 16.04 (64-bit)
- Browser and version: Chromium Version 58.0.3029.81

Steps to reproduce:

1. open codepen example
2. click on image
3. :peka:
![selection_531](https://cloud.githubusercontent.com/assets/1944061/25828296/21351506-3458-11e7-86de-cd196e616c5c.png)

Use-case: preview image with different aspect ratio than original.

**Comment by kingdido999** [comment]
Hmm...the only practical use-case I can think of is having a thumbnail (like square-shaped) zooming into its original form which has a different aspect ratio. Don't have an answer right now, but I will definitely think about it.

Another issue to keep in mind is that if we choose to show different aspect ratios, then the zoom animation might become a bit ugly once the img src suddenly changed. In other words, keep the same aspect ratio makes the transition smooth and consistent. Just some thoughts, let me know what you think.

**Comment by artaommahe** [comment]
@kingdido999 while adding lib to my app and testing different cases i found funny partial uglyhack for this
https://codepen.io/anon/pen/jmYLXy?editors=1010

**Comment by kingdido999** [comment]
@artaommahe I don't really like the idea of having different aspect ratio images in the first place. The original source was intended to be the exact same image as the default source, except having a "higher resolution". So this is our prerequisite here. You can always modify the width and height of zoomed in image via callback if you really want to.
