### ISSUE TITLE
No zooming when img as link

### ISSUE THREAD

**Issue by Rumi1111** [kingdido999/zooming#331]
Is there a way to have the zooming disabled on images that act as a link?
Thank you for the great program!

**Comment by kingdido999** [comment]
Could you be more specific on this use case? Note that you can always [listen](https://kingdido999.github.io/zooming/docs/#/api-reference?id=listen) to the images with specific css class (and make sure you don't add this class to "images that act as a link").

**Comment by Rumi1111** [comment]
Yes, of course! Thank you!
