### ISSUE TITLE
Zooming doesn't work when div content set dynamically

### ISSUE THREAD

**Issue by HeliosDev** [kingdido999/zooming#35]
Hello, I have an issue with your otherwise excellent library.

If I set all the attributes for zooming in the HTML, no problem, but if I try something like this:

```javascript
$infoPanel.html("<img src='contenuti/ap" + thumbID + ".png' data-action='zoom' data-original='contenuti/ap" + thumbID + "_z.png'/>");
```

`(html: <div id="infoPanel"></div>)`

zoom doesn't work anymore.

Am I doing anything wrong or is it supposed to be like this?

Thank you.

**Comment by HeliosDev** [comment]
Sorry...

```javascript
$infoPanel.html("<img src='contenuti/ap" + thumbID + ".png' data-action='zoom' data-original='contenuti/ap" + thumbID + "_z.png'/>");
```

**Comment by HeliosDev** [comment]
Never mind, I set the zooming by code and now everything works ok.

Cheers.

**Comment by kingdido999** [comment]
Yes, you need to manually listen to those elements created/modified after DOM content has been loaded.
