### ISSUE TITLE
Handle horizontal scrolling to exit the overlay

### ISSUE THREAD

**Issue by cynddl** [kingdido999/zooming#36]
The current behavior is to exit the zoomed overlay when the user scrolls more than ```scrollThreshold```. However, the library only supports vertical scrolling, and horizontal webpages just become blank as the user scrolls and scrolls.

A solution would be to implement ```lastScrollPositionX``` and ```lastScrollPositionY``` instead of just ```lastScrollPosition```, and check for both ```deltaX``` and ```deltaY```. I'm willing to send a tentative workaround pull request if needed.

**Comment by kingdido999** [comment]
@cynddl Do you mind creating an example to show what does it look like on horizontal webpages on [codepen](https://codepen.io/kingdido999/pen/zwQWpm) (I have included the library)?

**Comment by kingdido999** [comment]
Close it for now, will reopen if further discussion is needed.

**Comment by cynddl** [comment]
@kingdido999, sorry for the delay. Please find below a example of an horizontal scrolling gallery:
https://codepen.io/Cynddl/pen/xrVmzV

As you can see, scrolling vertically does not stop the overlay effect, and scrolling horizontally completely mess up with the layout.

**Comment by kingdido999** [comment]
@cynddl Thanks for the demo. I've made the fix and verified from my side. It would be great if you can test it out against the latest master.

**Comment by cynddl** [comment]
Yes, it works perfectly. Thanks for the quick answer!
