### ISSUE TITLE
How to dinamically initialaze new photoes

### ISSUE THREAD

**Issue by armbull** [kingdido999/zooming#37]
Hello
How to dinamically initialaze new photoes? 
I add new photo with markup of `data-action='zoom'` then I add code:
```
var zooming = new Zooming({
	  defaultZoomable: 'img[data-action="zoom"]'
	});
```
After that it doesn't work properly
I can not find re-init or rebuild function in your documentation
How to do that?
Thanks

**Comment by kingdido999** [comment]
You need to listen to images after you created them dynamically:

```js
var zooming = new Zooming()

// Create new images with a specific class, for example, "zoomable"

zooming.listen('.zoomable')
```

**Comment by kingdido999** [comment]
Though your code should also work as long as it's called after new images were created.

**Comment by armbull** [comment]
Thanks. It works.
