### ISSUE TITLE
How to detect target element when it zoomed via function onBeforeOpen/onBeforeClose

### ISSUE THREAD

**Issue by armbull** [kingdido999/zooming#38]
Hello,
I've read your documentation and I can not get automatically selector ID of target photo when it zoomed. I want to manipulate with it by onBeforeOpen/onBeforeClose function.
How to get target photo ID via function or something else?
Thanks

**Comment by armbull** [comment]
I found a solution
`var zooming = new Zooming({
          //...
	  onBeforeOpen: function(target){
		console.log(target);
	  },
        //...
});`

**Comment by kingdido999** [comment]
Yes, you will have the `target` as callback argument.
