### ISSUE TITLE
[Crash] Bug with effect of zoom on hover while grabbed is outside of photo

### ISSUE THREAD

**Issue by armbull** [kingdido999/zooming#39]
About your [example](https://jsfiddle.net/kingdido999/gj6xp1dn/1/) of zooming while hovering
It is this [issue](https://github.com/kingdido999/zooming/issues/31)
When photo was zoomed via hover event if you begin to grab and your mouse is outside of image, photo is zooming out and it doesn't work anymore. It works only after reload a page.
How to fix it?
I think it need add if statement to
```
img.addEventListener('mouseleave', function onMouseLeave (event) {
			zooming.close()
		  })
```
Something like this
``` 
img.addEventListener('mouseleave', function onMouseLeave (event) {
    if(grabbedFunc_is_not_run){
	zooming.close()
    } else if (grabbedFunc_release)
        {zooming.close()
    }
 })
```
But I didn't found this events in ducumentation. Maybe it needs to work with drag, dragend events, but maybe there is an easier way.
Thanks

**Comment by kingdido999** [comment]
I have updated the [example](https://jsfiddle.net/kingdido999/gj6xp1dn/3/) to fix this issue. We basically need to check that the mouse is not pressing down when the mouse is leaving the image:

```js
img.addEventListener('mouseleave', function onMouseLeave (event) {
  if (event.buttons !== 1) {
    zooming.close()
  }
})
```

**Comment by kingdido999** [comment]
@armbull I also figured [this](https://help.github.com/categories/writing-on-github/) might be helpful to you on writing/referencing issue or documentation on GitHub.
