### ISSUE TITLE
Click on overlay does not close image after 1.1.6 with `enableGrab: false`

### ISSUE THREAD

**Issue by artaommahe** [kingdido999/zooming#40]
- OS: Ubuntu 16.04
- Browser and version: Chromium Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

Steps to reproduce:
1. open https://codepen.io/anon/pen/owWmrg?editors=1010
2. click on image
3. click on white overlay around image - nothing happens
4. set `enableGrab: true`
5. click on image
6. click on white overlay around image - image properly zoomed out

As i debugged `instance.close` method has wrong `this` reference on overlay click - clicked element instead of zooming instance.
It works with 1.1.6 due to explicit method call instead of method reference passed as listener callback
```js
this.el.addEventListener('click', () => this.instance.close())
```

**Comment by kingdido999** [comment]
@artaommahe you are right, the callback function for overlay click event has wrong `this` reference. I changed the code back to explicit method call:

```js
this.el.addEventListener('click', () => this.instance.close())
```

Alternatively, bind the correct context will also work:

```js
this.el.addEventListener('click', this.instance.close.bind(this.instance))
```

**Comment by kingdido999** [comment]
@artaommahe Interestingly, since the code had wrong `this` context, how could it even work for `enableGrab: true`? I just realized that there are additional event listeners attached to `document` when grab is enabled, which means click on `document` will also trigger close event :)

```js
if (this.options.enableGrab) {
  toggleGrabListeners(document, this.handler, true)
}
```
