### ISSUE TITLE
responsive image

### ISSUE THREAD

**Issue by jimblue** [kingdido999/zooming#41]
I see an issue in [demo](http://desmonding.me/zooming/) page:

- OSX version 10.12.5
- Chrome version 61.0.3141.7

Steps to reproduce:

1. go to the  [demo page](http://desmonding.me/zooming/)
2. click on an image to open zooming
3. try to resize the windows

I'm not sure it's a bug or a missing feature but here image are not responsive.

If it's not a bug it could be nice to add this option into `zooming.js` core, it shouldn't be difficult to do.

Anyway thanks @kingdido999 for this nice plugin I like it a lot 😄 !

**Comment by kingdido999** [comment]
@jimblue I'm glad you liked it! I would say it's a minor bug, maybe we should make it responsive as we resize the window.

**Comment by jimblue** [comment]
Yes it could be nice.
Just leaving here the function I use to execute a script au resize.

```js
// import throlle from lodash
import throttle from 'lodash/throttle'

// function to handle resize actions
const onResize = (method) => {
  // Cutting the mustard
  // http://webfieldmanual.com/guides/cutting-the-mustard.html
  if (window.requestAnimationFrame && document.documentElement.classList) {
    // requestAnimationFrame
    // http://www.paulirish.com/2011/requestanimationframe-for-smart-animating/
    let _requestAnimationFrame = window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame
    // Throttle events and requestAnimationFrame
    let resizeHandler = throttle(function () {
      _requestAnimationFrame(method)
    }, 300)
    // Listening for events
    if (window.addEventListener) {
      addEventListener('resize', resizeHandler, false)
    } else if (window.attachEvent) {
      window.attachEvent('onresize', resizeHandler)
    } else {
      window.onresize = resizeHandler
    }
  }
}
```

Then I simply use like this: `onResize(functionToExecuteOnResize)`

**Comment by kingdido999** [comment]
@jimblue I applied max width and height for opened image style instead of fixed size. It's not a full solution as the image goes out of the window a bit due to scaling, but at least it makes the image responsive and keeps the image aspect ratio.

I would prefer not to involve `onresize` event handler for this issue, mainly because it adds a lot of code (throttle function and recalculate CSS transform) which in my opinion does not worth it. I might come up with something else to fit the image correctly. Let me know if you have any other suggestions.

**Comment by jimblue** [comment]
@kingdido999 I understand your logic to keep your plugin optimise and small, but is this that heavy to only add `onresize`? I could be use also for mobile when switching from landscape to portrait.
Maybe an other solution could be css viewport scale in css and not percentage?

**Comment by kingdido999** [comment]
@jimblue It would require a lot more effort than just `onresize` function to make image responsive to window resize. I tried css viewport but it didn't work out. Unfortunately I decide not to implement this feature, but I'm open to any potential solutions or PRs.

**Comment by jimblue** [comment]
Hi @kingdido999 ! Sorry to heard you're not going to implement this feature. 😭 😭 😭
In my mind adding `onresize` to make image responsive would take less than 30 lines, I tough it was just matter of refreshing the math you're using to position the image on zooming...
Also I'm afraid that I can't help more, I'm absolutely not a developer.
So I hope you'll reconsider the benefit of this feature soon 😄 !
In my opinion it's an important one considering that mobile users are more than desktop users. And going from portrait to landscape when looking at a picture is a common habit. (please tell me you're convinced now ?)

**Comment by kingdido999** [comment]
@jimblue Hey I totally understand you...I will definitely come back to this issue later, just don't have enough bandwidth at this moment😅  (you know, writing software fatigues people XD)

I'm also kinda curious why/how do you use this library, something related to your work?

**Comment by jimblue** [comment]
@kingdido999 nice to hear you'll come back on this later 😄.
I was thinking last night to some kind of fix. Why not just kill zoomed image on resize?

(I'm changing the design of my website, will go from lightgallery.js to your library for my photos)

**Comment by kingdido999** [comment]
@jimblue Actually your idea makes a lot of sense to me the more I think about it! Now zoomed image will be closed on window resize (and device orientation change) by default, user can opt-out by setting the new option `closeOnWindowResize: false`. Please try it out on [demo](http://desmonding.me/zooming/) page!

**Comment by jimblue** [comment]
@kingdido999 good job! That's look natural and resolve the issue 👍 !
Thank you so much man

**Comment by kingdido999** [comment]
@jimblue The change has been made into version 1.2.4 😄

**Comment by jimblue** [comment]
@kingdido999, I've just upgrade to 1.2.4 but it doesn't like on the demo page.

**Comment by jimblue** [comment]
working great thanks!
