### ISSUE TITLE
Implement absolute image position with fixed position wrapper

### ISSUE THREAD

**Issue by kingdido999** [kingdido999/zooming#44]
A fixed position wrapper with absolute image position and an image placeholder (since the actual image no longer takes space) would resolve some existing issues. This would require a big portion of rewrite though.

**Comment by jimblue** [comment]
would be amazing 💯  !

**Comment by kingdido999** [comment]
I've been trying to finish the implementation, but I couldn't find a feasible solution that doesn't affect existing behaviour/animation. I know this might be disappointing to you guys,  but I'll stop experimenting with this and accept that some issues/limitations will carry on at this point.
