### ISSUE TITLE
Add pkg.module field to package.json for ES6 module import

### ISSUE THREAD

**Issue by mahish** [kingdido999/zooming#49]
Im using `"rollup": "^0.56.1",`  to bundle my js. So I would love to be able to import ES6 modules by default if possible. In case of Zooming package, it is not possible for me at the moment. 

However, i can make it work when I add this line `"module": "src/index.js"` to the Zooming `package.json` so my rollup can find the (source) es6 module and import it simply as that `import Zooming from 'zooming';`. See https://github.com/rollup/rollup/wiki/pkg.module

**Comment by kingdido999** [comment]
It should be available in `1.3.1` now. Please test it out and let me know 😄

**Comment by mahish** [comment]
Thanks.

1. Im getting this error in console when zooming is on the page `Uncaught TypeError: b is not a function at HTMLDocument.<anonymous> (zooming.js:196) (anonymous) @ zooming.js:196`
2. Someone with webpack should test it as well
3. Hmm... Im not sure if a link to the source file is the safest way how to do it. You might use rollup to bundle it as one final module into the `build` folder maybe? I like how jump.js do it: https://github.com/callmecavs/jump.js

**Comment by kingdido999** [comment]
Thanks for the feedback. Yes it makes sense to build a final module. I'm also thinking leverage the latest Rollup API #50 and then build different modules. I might need some time to refactor them, let me know if you're interested working on them (I created a branch `update/dep` with the latest rollup version).

**Comment by mahish** [comment]
Working on it now.

**Comment by kingdido999** [comment]
@mahish Try `1.4.0` now :)

**Comment by mahish** [comment]
Works fine for me, thanks! Although, I still keep getting an error with Zooming in my project (on line `666:32` in `zooming.module.js`) which is not related to this issue! I also have a new proposition regarding `srcset` attribute on `<img>`:)
