### ISSUE TITLE
Error: Couldn't find preset "es2015-rollup"

### ISSUE THREAD

**Issue by mahish** [kingdido999/zooming#54]
Getting this error when compiling my javascript: `Error: Couldn't find preset "es2015-rollup" relative to directory "/Users/…/node_modules/zooming"` 

### Solution:
It can be fixed by removing `.babelrc` from the npm package (adding it to `.npmignore`). It is obviously good practice if you google it around. `.babelrc` with specified preset present in npm package makes my Babel to look for the preset specified in the package which I dont have installed (`es2015-rollup` in the package vs. `env` in my project).

Dont know why I didnt get this error before :(

**Comment by kingdido999** [comment]
Please try the fix in `1.4.1`.

**Comment by mahish** [comment]
No error now. Thanks!

**Comment by mahish** [comment]
@kingdido999 … and thank you for this lovely script btw:)
