### ISSUE TITLE
Improve UI testing

### ISSUE THREAD

**Issue by kingdido999** [kingdido999/zooming#55]
Currently, only very basic Zooming APIs are tested through mocha in browser. We should probably include some end-to-end tests by leveraging a web automation framework.

[awesome-test-automation](https://github.com/atinfo/awesome-test-automation/blob/master/javascript-test-automation.md#web-ui-test-automation)

**Comment by kingdido999** [comment]
Try [TestCafe](https://github.com/DevExpress/testcafe).

**Comment by kingdido999** [comment]
Seems long press in testcafe is not supported...See this [issue](https://github.com/DevExpress/testcafe/issues/2054).

**Comment by kingdido999** [comment]
[cypress](https://github.com/cypress-io/cypress) runs tests directly in the browser, it looks very promising!

**Comment by kingdido999** [comment]
- [x] Happy path test case.
- [ ] API tests (listen, open, close, etc).
- [ ] Options tests.

**Comment by kingdido999** [comment]
Having trouble simulating long press. The following code does not zoom the image further in:

```js
describe('Demo Page Test', function () {
  beforeEach(function () {
    cy.visit('/index.html')
  })

  it('Opens and closes the first image', function () {
    cy.get('#img-default')
      .click()
      .wait(1000)
      .trigger('mousedown')
      .wait(1000)
      .trigger('mouseup')
      .wait(1000)
      .click()
  })
})
```

**Comment by kingdido999** [comment]
Figured out:

```js


describe('Demo Page Test', function () {
  beforeEach(function () {
    cy.visit('/index.html')
  })

  it('Open, grab, release and close the image', function () {
    cy.get('#img-default')
      .click()
      .wait(500)
      .trigger('mousedown', { button: 0 })
      .wait(500)
      .trigger('mouseup', { button: 0 })
      .wait(500)
      .click()
  })
})
```

**Comment by mahish** [comment]
@kingdido999 Recently, Ive been playing with Cypress as well. What `button: 0` means actually? Didnt find any info about in docs. Thanks and sorry for offtopic.

**Comment by kingdido999** [comment]
@mahish In this case, it means main/left button on input device (mouse, track pad, .,etc). You can find more details [here](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button).
