### ISSUE TITLE
Zooming with Bootstrap carousel

### ISSUE THREAD

**Issue by winterdedavid** [kingdido999/zooming#57]
First of all, this is a great project, thanks! However, I am having difficulties using this project along with a Bootstrap carousel, I have forked your page on codepen and have integrated a default Bootstrap v4 carousel. If I then click on an image in the carousel, the zooming animation gets triggered but the screen stays blank, seems to be on multiple browsers. Any idea what is causing this? I assume it's likely not related to the zooming.js itself, but due to some technicality in the Bootstrap framework, so apologies if this would not be the right place to ask this. Thanks in advance.

https://codepen.io/winterdedavid/pen/RQMoNN

**Comment by kingdido999** [comment]
Well...this is a known issue/limitation of this library mentioned in README as #22. Basically, images will not be visible after zoom-in if its parents have CSS style `overflow: hidden`. In your case, the element `.carousel-inner` is causing the issue.

A potential solution is to remove `overflow: hidden` before opening the image and add it back once closed:

```js
const carouselInner = document.querySelector('.carousel-inner')

new Zooming({
  onOpen: function () {
    carouselInner.style.overflow = 'visible'
  },
  onClose: function () {
    carouselInner.style.overflow = 'hidden'
  }
});
```

I haven't tested it though, just something off the top of my head.

**Comment by winterdedavid** [comment]
Thanks for the quick reply! I have done a static override to `overflow: visible` on the `.carousel-inner` element, however it doesn't make a difference, I also updated the codepen.
```html
...
<div class="carousel-inner" style="overflow: visible;">
   ...
</div>
...
```

**Comment by kingdido999** [comment]
Hey @winterdedavid I don't think I have bandwidth to investigate this further, so I will close this issue now. As I said it might be a limitation of this library. As a side note, it may not be a good UX choice to combine image zooming and carousel together, seems a bit weird to interact in my opinion.
