### ISSUE TITLE
Support for data-original with srcset

### ISSUE THREAD

**Issue by migueldemoura** [kingdido999/zooming#59]
Hey, pretty cool project!

I noticed that the `data-original` functionality doesn't work with img's `srcset`. Replacing the image's src doesn't change the image since srcset takes precedence. This is usually used for responsive images.

Edit: just noticed this commit https://github.com/kingdido999/zooming/commit/717b997f89dca2156d1c4516183d86042886326f, which isn't included in the latest version.

Closing this issue.

**Comment by migueldemoura** [comment]
Could you push a new minor version with this fix? @kingdido999

**Comment by kingdido999** [comment]
Done. The fix is in `1.4.2`.
