### ISSUE TITLE
Error when closing zoom by clicking outside of image

### ISSUE THREAD

**Issue by daxhns** [kingdido999/zooming#6]
When you zoom in, and then zoom out by clicking OUTSIDE of zoomed in image, there is an error in the console:

`Uncaught TypeError: cb is not a function(…)`

Tried on Chrome and Firefox on Windows.

**Comment by kingdido999** [comment]
It should be fixed. Please verify.

**Comment by daxhns** [comment]
Yes, fixed, works without error now. good job.

**Comment by daxhns** [comment]
BTW, I see that you have removed build/zooming.js file from the respository... was this on purpose or a mistake? If it was on purpose, how should we create that file from src?

**Comment by kingdido999** [comment]
Yes I removed it because given the source map, we can inspect the actual source code in browser dev tool, so I removed the unminified version. But after thought on this, I'll bring it back as the original transpiled code is not available for people anymore. Closing this now.
