### ISSUE TITLE
Compatibility with Turbolinks

### ISSUE THREAD

**Issue by migueldemoura** [kingdido999/zooming#68]
[Turbolinks](https://github.com/turbolinks/turbolinks) adds an event for when a page is loaded, `turbolinks:load`, and the following code in zooming will result in a double class instantiation:

``` javascript
listen(document, 'DOMContentLoaded', function initZooming() {
  new Zooming();
});
```

if the user then adds:

``` javascript
document.addEventListener('turbolinks:load', function() {
    new Zooming({customOptionsHere});
})
```
This makes zooming unusable with Turbolinks. Are you aware of any way for me to avoid this other than forking and removing the listen() call?

**Edit**: I've spent some more time looking at this, and I think this has nothing to do with Turbolinks.
That initialization doesn't seem to allow the user to change the options associated with the default zoomable images.
The only benefit I see for this behaviour is to allow a user to simply load the .js and get the default zoom on the default items. This can also be achieved with:

``` javascript
document.addEventListener('DOMContentLoaded', function() {new Zooming();})
```

Would you consider either modifying this or removing the call altogether?
![bug](https://user-images.githubusercontent.com/9093796/38282357-986e6d0e-37a7-11e8-9561-9de04a835482.gif)

**Comment by migueldemoura** [comment]
Let me know if I can be of some help!

**Comment by kingdido999** [comment]
- [ ] Remove Zooming initialization call.
- [ ] Update doc.

**Comment by kingdido999** [comment]
@migueldemoura I have includes a few issues into a [milestone](https://github.com/kingdido999/zooming/milestone/1), I will take care of this issue but I could really use some help from you on #69 and #55 ?

**Comment by kingdido999** [comment]
What’s your thoughts on removing option ‘defaultZoomable’ altogether and use ‘listen()’ API instead? In this way it simplifies API usage and I feel like ‘.listen()’ is a lot more semantic. Also it’s explicit in a way that let’s user decide when to listen to target images.

**Comment by kingdido999** [comment]
Initialization call is removed in [2.0.0](https://github.com/kingdido999/zooming/releases/tag/2.0.0).

**Comment by migueldemoura** [comment]
Sorry, I've been quite busy these days. As for the `defaultZoomable`, I feel it is a widespread pattern, but understand you wanted it removed.

``` javascript
new Zooming({smth}).listen('.zooming')
```
The above is quite simple as well.
