### ISSUE TITLE
Redesign demo page

### ISSUE THREAD

**Issue by kingdido999** [kingdido999/zooming#69]
I would like to incorporate more zooming features into the demo page, possibly through a more dynamic interaction rather than toggling features on and off. It would be really cool if we can have interactive demos like what [observable](https://beta.observablehq.com/) and [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat) does. For example, we can have rows of sections where each section demos a specific feature. Each section contains image(s) + editor with corresponding configuration. And the demo page is going to be the source for regression test as well.

Just some thoughts, any suggestions are welcome!

**Comment by migueldemoura** [comment]
Really like the idea. Where can I see the MDN interactive examples? I tried the link you provided but couldn't find them.
