### ISSUE TITLE
Is it possible to zoom masked image (object-fit: cover) to reveal the full image?

### ISSUE THREAD

**Issue by mattjis** [kingdido999/zooming#78]
I'm created a flex container that squeezes multiple images side by side but when they're clicked (to zoom) I want them to no longer be squished.. 

Is this possible?

**Comment by kingdido999** [comment]
Close it due to inactivity.

**Comment by MXTcomunica** [comment]
As suggested by @kingdido999, in my case I fixed the issue in this way:

```
const zooming = new Zooming({
  onOpen: function (target) {
    target.style.objectFit = 'fill';
  },
  onBeforeClose: function (target) {
    target.style.objectFit = 'cover';
  }
})

zooming.listen('.img-zoomable')
```
