### ISSUE TITLE
press esc when grabbing, the zoom immediately restore without transition and the zoom cannot work anymore

### ISSUE THREAD

**Issue by liximomo** [kingdido999/zooming#8]
action to recurrence
1. open [demo](http://desmonding.me/zooming/) page
1. zoom in any  image
1. grap and keep
1. press esc

**Comment by kingdido999** [comment]
@liximomo I can reproduce this issue. Working on it.

**Comment by kingdido999** [comment]
Fixed. Now the image will go back to its previous state before closing out. Notice that if you do not release your mouse before the image is fully closed, it will reopen the image once you released your mouse. Might fix this in the future, although it's not a showstopper:)
